apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-tioh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-tioh
    app.kubernetes.io/part-of: e2e-springboot
  name: devfile-sample-java-springboot-basic-tioh
  namespace: e2e-demos-rbrg-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-java-springboot-basic-tioh
    weight: null
status: {}
